services:
  app:
    build: .
    container_name: python-server
    command: python src/main.py
    #command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    volumes:
      - .:/code
  #frontend:
  #  build: ./ObjectDetectionFront  # Ruta al directorio del proyecto de React
  #  container_name: react-app
  #  command: npm run dev  
   # ports:
  #    - 5173:5173
   # volumes:
    #  - ./ObjectDetectionFront:/app



  